// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYriBjAp6Fz4Yne4tWWmOMu0tga8clq5A',
    appId: '1:847222172281:web:e879534a16667be4bf82a8',
    messagingSenderId: '847222172281',
    projectId: 'c2b-shopping-app',
    authDomain: 'c2b-shopping-app.firebaseapp.com',
    storageBucket: 'c2b-shopping-app.firebasestorage.app',
    measurementId: 'G-ZXCY482JVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA-lxHC_my64jRjAGRwpp9FyAE7Gt_evg',
    appId: '1:847222172281:android:02bc83a86f1babdcbf82a8',
    messagingSenderId: '847222172281',
    projectId: 'c2b-shopping-app',
    storageBucket: 'c2b-shopping-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgaqL4GsiNQ-N0uzx3JrDdgCIlcIf2NHo',
    appId: '1:847222172281:ios:565823ba09455becbf82a8',
    messagingSenderId: '847222172281',
    projectId: 'c2b-shopping-app',
    storageBucket: 'c2b-shopping-app.firebasestorage.app',
    iosClientId: '847222172281-tjqvb4i2gsci7vikkmiihv3cok7vqpdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgaqL4GsiNQ-N0uzx3JrDdgCIlcIf2NHo',
    appId: '1:847222172281:ios:565823ba09455becbf82a8',
    messagingSenderId: '847222172281',
    projectId: 'c2b-shopping-app',
    storageBucket: 'c2b-shopping-app.firebasestorage.app',
    iosClientId: '847222172281-tjqvb4i2gsci7vikkmiihv3cok7vqpdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYriBjAp6Fz4Yne4tWWmOMu0tga8clq5A',
    appId: '1:847222172281:web:8977213cb25a9da1bf82a8',
    messagingSenderId: '847222172281',
    projectId: 'c2b-shopping-app',
    authDomain: 'c2b-shopping-app.firebaseapp.com',
    storageBucket: 'c2b-shopping-app.firebasestorage.app',
    measurementId: 'G-44J4NHYQS5',
  );
}
